class Foo
  fun assign_self_err(self var)
    # this should be an error
    self = "value"
  end

  fun assign_self_okay(self var)
    # this shouldn't 
    self = Foo with ?
  end
end

# both should be an error
puts (Foo with ?).assign_self_err
puts (Foo with ?).assign_self_okay

# only the first one should be an error
var my_foo = Foo with ?

puts my_foo.assign_self_err
puts my_foo.assign_self_okay
