rec Foo
end

idea for Foo
  fun assign_self_err(self var)
    # this should be an error
    self = "value"
  end

  fun assign_self_okay(self var)
    # this shouldnâ€™t
    self = Foo with ..
  end
end

fun main
  # both should be an error
  print (Foo with ..).assign_self_err
  print (Foo with ..).assign_self_okay

  # only the first one should be an error
  var my_foo = Foo with ..

  print my_foo.assign_self_err
  print my_foo.assign_self_okay
end
